#!/bin/bash

# Install contrib nbextensions
jupyter contrib nbextension install --user

# Enable specific nbextension
jupyter nbextension enable load_tex_macros/main

# Install and enable RISE
jupyter-nbextension install rise --py --user
jupyter-nbextension enable rise --py --user
